name: Pull-Request-Test

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-PR-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven validate
        run: mvn validate
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-PR-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven compile
        run: mvn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-PR-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven test
        run: mvn test
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-PR-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven package
        run: mvn package
  verify:
    runs-on: ubuntu-latest	
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-PR-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Verify with h2
        run: mvn verify -P h2
      - name: Verify with mysql
        run: mvn verify -P mysql