name: Pull-Request-Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest	
      steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run maven
        run: mvn clean verify -P h2