name: Master-integration

on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest	
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-MASTER-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run maven
        run: mvn clean verify -P h2