name: Pull-Request-Test

on:
  push:
    branches-ignore:
      - 'master'


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-PR-${{ hashFiles('**/pom.xml') }}
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven validate
        run: mvn validate
      - name: Upload validate home
        uses: actions/upload-artifact@v1
        with:
          name: validate-home
          path: ~

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download validate home
        uses: actions/download-artifact@v1
        with:
          name: validate-home

      - name: Maven compile
        run: mvn compile
      - name: Upload compile home
        uses: actions/upload-artifact@v1
        with:
          name: compile-home
          path: ~

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download compile home
        uses: actions/download-artifact@v1
        with:
          name: compile-home
      - name: Maven test
        run: mvn test
      - name: Upload test home
        uses: actions/upload-artifact@v1
        with:
          name: test-home
          path: ~

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download test home
        uses: actions/download-artifact@v1
        with:
          name: test-home
      - name: Maven package
        run: mvn package
      - name: Upload package home
        uses: actions/upload-artifact@v1
        with:
          name: package-home
          path: ~

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download package home
        uses: actions/download-artifact@v1
        with:
          name: package-home
      - name: Maven verify with h2
        run: mvn verify -P h2
      - name: Maven verify with mysql
        run: mvn verify -P mysql
      - name: Upload backend artifact
        uses: actions/upload-artifact@v1
        with:
          name: backend
          path: backend/target/semerusocial-backend.war
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v1
        with:
          name: frontend
          path: frontend/target/semerusocial.war
